### PR TITLE
#56 Focus Order (BasedOn main)

### PR DESCRIPTION
**Pull request by aromaine-unlv**
This pull request aims to tackle issue #56. The main problem was that Shift+Tab did not work when focus was on the top right button in the team members modal. In order to resolve this issue I implemented our new datim-modal library, which makes the modals more accessible and handles focus tracking.

### Team Page
- Converted every modal to use new datim-modal library
  - Fixes the Shift+Tab bug for all modals
### style.css
- Added a media query style to allow datim modals to be responsive for smaller screens

### CODE REVIEW

**Comment by aromaine-unlv** [comment]
Hey @Kelvyn-Meyers, I have updated the datim-modal.js file to match the one in the main DATIM repository. I have also refactored all of the modals to use the new logic for Bootstrap modals and I removed my modal from the team page. Everything seems to be working great, but let me know if you find anything else that I missed.

**Review by Kelvyn-Meyers — CHANGES_REQUESTED** [review]
Hi @aromaine-unlv,

The only bug I've run into is when you try to press ESC to close these dialogs. It looks like its causing a console error to appear:

image

Though I don't see this happening at DATIM in the current master branch.

**Comment by aromaine-unlv** [comment]
Hey @Kelvyn-Meyers, I resolved the issue you mentioned. This error does not actually affect functionality and is probably why I didn't catch it when testing this pull request. I believe that the modal is being closed by my escape key listener event before my Bootstrap listener, which is why there is a conditional to check whether the current target of the Bootstrap modal is open anymore, however the browser doesn't like that my conditional was checking against an undefined value. I wrapped the conditional in a additional one that makes sure the getCurrentDialog didn't return undefined. I hope that all makes sense, if you have any other questions or find anything else let me know.

**Review by Kelvyn-Meyers — APPROVED** [review]
Nice job @aromaine-unlv! This is working well on all of the employee profiles. Ready to merge.

**Pull request merged**
