### PR TITLE
#209 (UNLV-FIA Homepage) Add Charles Ballesteros Profile to Team Page. (Based On main)

### PR DESCRIPTION
**Pull request by ballec6**
This pull request is for issue #209 

## Code Changes

1. Added CJ Ballesteros' Profile

- Note that Charles Joseph Ballesteros was too long for the box and would mess up formatting, so it was shortened to CJ Ballesteros.
- Added Picture, as well as making sure the button leading to the profile works.
- Added Name, Job Title, Work Location, Email, Biography, Proficient Skills, and Improvement Goals

### CODE REVIEW

**Review by DorffZ — COMMENTED** [review]
This looks right, but I know you have more than 1 skill!

**Comment by ballec6** [comment]
> This looks right, but I know you have more than 1 skill!

Haha, I'm still getting there with other skills, but thank you!!

**Review by Rosadc1 — APPROVED** [review]
Looks great! Good Job!

**Review by Lais3 — APPROVED** [review]
Cool, looks good!! :smile:

**Review by Kelvyn-Meyers — APPROVED** [review]
Nice work here @ballec6, and good compromise to the text-wrapping situation. Ready to merge!

**Pull request merged**
